export { default as Home } from './home/Home'
export { default as About } from './About/About'
export { default as Contact } from './ContactUs/Contact'
export { default as Blog } from './Blog/Blog'
export { default as Posts } from './Posts/Posts'
export { default as Post } from './Post/Post'
export { default as Bloger } from './Bloger/Bloger'
export { default as ErrorPage } from './ErrorPage/ErrorPage'